language: go

go:
- "1.13"
before_script: go get -u golang.org/x/lint/golint
jobs:
  include:
    - stage: lint
      script: go list ./... | grep -v /vendor/ | xargs -n 1 golint
    - stage: unit tests
      script: go test -v ./...