{
 "title": "Self-stabilizing URB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Communication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sent/received messages",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(udp_client_msg_count)", "legendFormat": "Sent messages" },
    { "expr": "sum(udp_server_msg_count)", "legendFormat": "Received messages" }
   ]
  },
  {
   "title": "Servers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(udp_server_msg_count) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(udp_client_msg_count) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Online processors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"self-stabilizing-urb\"} == 1)"
    }
   ]
  },
  {
   "title": "# broadcasted messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(urb_broadcasted_messages_count and up{job=\"self-stabilizing-urb\"})"
    }
   ]
  },
  {
   "title": "# lost msgs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(urb_broadcasted_messages_count and up{job=\"self-stabilizing-urb\"}) - min(urb_delivered_messages_count and up{job=\"self-stabilizing-urb\"})"
    }
   ]
  },
  {
   "title": "# nodes missing msgs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"self-stabilizing-urb\"}) - (count((urb_delivered_messages_count and up{job=\"self-stabilizing-urb\"}) == scalar(sum((urb_broadcasted_messages_count and up{job=\"self-stabilizing-urb\"})))) OR vector(0))"
    }
   ]
  },
  {
   "title": "# fatal errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(udp_client_error_count{error_type=\"fatal_error\"}) OR vector(0) + (sum(udp_server_error_count) OR vector(0))"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Broadcast rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(urb_broadcasted_messages_count[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(urb_delivered_messages_count[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "urb_message_delivery_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Server throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(udp_server_msg_count[30s])",
     "legendFormat": "{{instance}} - sender {{sender_id}}"
    }
   ]
  },
  { "title": "Failure detectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Trusted processors - theta fd",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "theta_fd_trusted_count", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Error types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(udp_server_error_count) by (error_type)",
     "legendFormat": "server_{{error_type}}"
    },
    {
     "expr": "sum(udp_client_error_count) by (error_type)",
     "legendFormat": "client_{{error_type}}"
    }
   ]
  },
  {
   "title": "Errors by processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(udp_client_error_count) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "# of delivered messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (urb_delivered_messages_count)",
     "legendFormat": "count"
    },
    {
     "expr": "max (urb_delivered_messages_count)",
     "legendFormat": "max"
    },
    {
     "expr": "min (urb_delivered_messages_count)",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "# of delivered messages by processor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "urb_delivered_messages_count", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}